apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: books
  name: books
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: books
