apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: recommendations
  name: recommendations
  namespace: default
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer
  selector:
    app: recommendations
status:
  loadBalancer: {}
